apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: movieapp
  template:
    metadata:
      labels:
        app: movieapp
        service: movieapp
    spec:
      containers:
        - name: movieapp
          image: nobsreg92.azurecr.io/dotnetcore/movieapp:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: movieapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: movieapp