---
- 
  hosts: localhost ## Run on the Ansible server itself
  connection: local 
  
  vars:
    resourceGroup: NoBSDevOps
    name: nginxwebapp
    containerName: nginxwebapp
    image: nginx:latest

  tasks: 
  - name: Create an Azure Container Instanceform
      azure_rm_containerinstance:
        resource_group: "{{ resourceGroup }}"
        name: "{{ name }}"
        containers:
          - name: "{{ containerName }}"
            image: "{{ image }}"
            ports:
              - 80
              - 443
